#!/bin/bash

CONTAINER_NAME=$1

if [ -z "$1" ]; then
    echo "Please provide a name for the container './run [container_name]'"
    exit 1
fi

if ! docker info > /dev/null 2>&1; then
  echo "Docker is not running..."
  exit 1
fi

docker stop ${CONTAINER_NAME}
docker rm ${CONTAINER_NAME}

docker build -t ${CONTAINER_NAME} .
docker run --name ${CONTAINER_NAME}  -dp 8080:8080 ${CONTAINER_NAME}